name: hostelapplication
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+4

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:

  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.2.4
  uuid: ^3.0.6
  provider: ^6.0.3
  rflutter_alert:
  date_time_picker:
  image_picker: ^0.8.5+3
  file_picker:
  image_downloader: ^0.31.0
  file: ^6.1.4
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.0
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  google_fonts: 4.0.3
  intl: 0.17.0
  json_path: 0.4.1
  page_transition: 2.0.4
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  shared_preferences_android: 2.1.0
  shared_preferences_ios: 2.1.1
  shared_preferences_platform_interface: 2.2.0
  shared_preferences_web: 2.1.0
  smooth_page_indicator: 1.0.1
  sqflite: 2.2.6
  timeago: 3.2.2
  url_launcher: 6.1.10
  url_launcher_android: 6.0.27
  url_launcher_ios: 6.1.4
  url_launcher_platform_interface: 2.1.2
  grouped_list: ^5.1.2
  firebase_storage_mocks: ^0.6.1


dev_dependencies:

  flutter_test:
    sdk: flutter
  bdd_widget_test: ^1.6.0
  build_runner:
  flutter_gherkin: ^2.0.0
  fake_cloud_firestore: ^2.4.1+1
  firebase_auth_mocks: ^0.11.0


flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/onboard/
  
  fonts:
    - family: Brazila
      fonts:
        - asset: assets/onboard/Cirka_regular.ttf
        - asset: assets/onboard/Cirka_blod.otf
        - asset: assets/onboard/Cirka_light.otf
       
