import 'package:flutter/material.dart';

class PrivacyPolicyPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Privacy Policy'),
        backgroundColor: Colors.orangeAccent,
      ),
      body: SingleChildScrollView(
        padding: EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Privacy Policy',
              style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 8.0),
            Text(
              'Last updated: July 13, 2023',
              style: TextStyle(fontSize: 12),
            ),
            SizedBox(height: 16.0),
            Text(
              'This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.',
            ),
            SizedBox(height: 8.0),
            Text(
              'We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Free Privacy Policy Generator.',
            ),
            SizedBox(height: 16.0),
            Text(
              'Interpretation and Definitions',
              style: TextStyle(fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 8.0),
            Text('Interpretation'),
            SizedBox(height: 4.0),
            Text(
              'The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.',
            ),
            SizedBox(height: 8.0),
            Text('Definitions', style: TextStyle(fontWeight: FontWeight.bold)),
            SizedBox(height: 4.0),
            Text('For the purposes of this Privacy Policy:'),
            SizedBox(height: 4.0),
            Text(
                '- Account means a unique account created for You to access our Service or parts of our Service.'),
            Text(
                '- Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.'),
            Text(
                '- Application refers to UniStay, the software program provided by the Company.'),
            Text(
                '- Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to UniStay.'),
            Text('- Country refers to: Nepal'),
            Text(
                '- Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.'),
            Text(
                '- Personal Data is any information that relates to an identified or identifiable individual.'),
            Text('- Service refers to the Application.'),
            Text(
                '- Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.'),
            Text(
                '- Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.'),
            Text(
                '- Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).'),
            Text(
                '- You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.'),
            SizedBox(height: 16.0),
            Text(
              'Collecting and Using Your Personal Data',
              style: TextStyle(fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 8.0),
            Text('Types of Data Collected'),
            SizedBox(height: 4.0),
            Text('Personal Data'),
            SizedBox(height: 4.0),
            Text(
              'While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:',
            ),
            SizedBox(height: 4.0),
            Text('- Email address'),
            Text('- First name and last name'),
            Text('- Phone number'),
            SizedBox(height: 4.0),
            Text('Usage Data'),
            SizedBox(height: 4.0),
            Text(
                'Usage Data is collected automatically when using the Service.'),
            SizedBox(height: 4.0),
            Text(
                'Usage Data may include information such as Your Device\'s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.'),
            SizedBox(height: 4.0),
            Text(
                'When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.'),
            SizedBox(height: 4.0),
            Text(
                'We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.'),
            SizedBox(height: 4.0),
            Text('Information from Third-Party Social Media Services'),
            SizedBox(height: 4.0),
            Text(
                'The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:'),
            SizedBox(height: 4.0),
            Text('- Google'),
            Text('- Facebook'),
            Text('- Instagram'),
            Text('- Twitter'),
            Text('- LinkedIn'),
            SizedBox(height: 4.0),
            Text(
                'If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service\'s account, such as Your name, Your email address, Your activities or Your contact list associated with that account.'),
            SizedBox(height: 4.0),
            Text(
                'You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service\'s account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.'),
            SizedBox(height: 4.0),
            Text('Information Collected while Using the Application'),
            SizedBox(height: 4.0),
            Text(
                'While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:'),
            SizedBox(height: 4.0),
            Text(
                '- Pictures and other information from your Device\'s camera and photo library'),
            SizedBox(height: 4.0),
            Text(
                'We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company\'s servers and/or a Service Provider\'s'),
            SizedBox(height: 8.0),
            Text('The Company may use Personal Data for the following purposes:'),
            SizedBox(height: 4.0),
            Text('- To provide and maintain our Service, including to monitor the usage of our Service.'),
            Text('- To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.'),
            Text('- For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.'),
            Text('- To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application\'s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.'),
            Text('- To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.'),
            Text('- To manage Your requests: To attend and manage Your requests to Us.'),
            Text('- For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.'),
            Text('- For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.'),
            SizedBox(height: 16.0),
            // Add more sections as needed
            Text(
              'Contact Us',
              style: TextStyle(fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 8.0),
            Text('If you have any questions about this Privacy Policy, You can contact us:'),
            SizedBox(height: 4.0),
            Text('- By email: unistay@hostel.com'),
          ],
        ),
      ),
    );
  }
}
