// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWZUwWep05XNf75MYZJHXoGt6gs3-b8AE',
    appId: '1:233117944548:web:2614e72fdfff836d4fbaf1',
    messagingSenderId: '233117944548',
    projectId: 'unistay-68d5e',
    authDomain: 'unistay-68d5e.firebaseapp.com',
    storageBucket: 'unistay-68d5e.appspot.com',
    measurementId: 'G-F3WCR0B0YF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnutxPlKBbxedNxWz-osOjPR7-r2O_l4o',
    appId: '1:233117944548:android:e240b6599d97043d4fbaf1',
    messagingSenderId: '233117944548',
    projectId: 'unistay-68d5e',
    storageBucket: 'unistay-68d5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO8eQS2eqY6tt71-NZJYZqdt1uOwzVKgA',
    appId: '1:233117944548:ios:7f21b154c801c9d94fbaf1',
    messagingSenderId: '233117944548',
    projectId: 'unistay-68d5e',
    storageBucket: 'unistay-68d5e.appspot.com',
    androidClientId: '233117944548-3ieoe5gelksap9fko9ku9m5ascs27ac0.apps.googleusercontent.com',
    iosClientId: '233117944548-v2v3u2kl90r97dkd8k87b1ec2u82edq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.unistay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO8eQS2eqY6tt71-NZJYZqdt1uOwzVKgA',
    appId: '1:233117944548:ios:7f21b154c801c9d94fbaf1',
    messagingSenderId: '233117944548',
    projectId: 'unistay-68d5e',
    storageBucket: 'unistay-68d5e.appspot.com',
    androidClientId: '233117944548-3ieoe5gelksap9fko9ku9m5ascs27ac0.apps.googleusercontent.com',
    iosClientId: '233117944548-v2v3u2kl90r97dkd8k87b1ec2u82edq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.unistay',
  );
}
